services:
  presentation:
    container_name: form_generator_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASESETTINGS__SWIFTCOPY_HOST: ${DATABASESETTINGS__SWIFTCOPY_HOST}
      DATABASESETTINGS__SWIFTCOPY_USER: ${DATABASESETTINGS__SWIFTCOPY_USER}
      DATABASESETTINGS__SWIFTCOPY_PASSWORD: ${DATABASESETTINGS__SWIFTCOPY_PASSWORD}
      DATABASESETTINGS__ELECATECOREAPIWRAPPERDEV_HOST: ${DATABASESETTINGS__ELECATECOREAPIWRAPPERDEV_HOST}
      DATABASESETTINGS__ELECATECOREAPIWRAPPERDEV_USER: ${DATABASESETTINGS__ELECATECOREAPIWRAPPERDEV_USER}
      DATABASESETTINGS__ELECATECOREAPIWRAPPERDEV_PASSWORD: ${DATABASESETTINGS__ELECATECOREAPIWRAPPERDEV_PASSWORD}